### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: FlightId  '5' not found in inputStream.

### ISSUE THREAD

**Issue by ghost** [mikejr83/TLMReaderLib#7]
When running the example (App.java) out of the box... 

```java
Exception in thread "main" java.lang.RuntimeException: FlightId  '5' not found in inputStream.
	at com.monstarmike.tlmreader.TLMReader.parseFlight(TLMReader.java:109)
	at com.monstarmike.tlmreader.TLMReader.parseFlight(TLMReader.java:32)
	at com.monstarmike.tlmreader.App.main(App.java:30)
----------------------------------------------------------------------
```

**Comment by mikejr83** [comment]
This might be related to the earlier issue that was noted for the wrong TLM file. Investigating.
